### ISSUE TITLE
More Python3 issues

### ISSUE THREAD

**Issue by tuxdna** [gofed/gofedlib#14]
In addition to the fixes done in https://github.com/gofed/gofedlib/issues/10 , here are a few more.

Below are the sequence of errors encountered running gofed cli tool on a sample go project:

```
$ gofedlib-cli --dependencies-main --dependencies-packages go-examples/
Traceback (most recent call last):
  File "/tmp/env3/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/go/functions.py", line 8, in project_packages
    return GoSymbolsExtractor(source_code_directory).extract().packages()
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/go/symbolsextractor/extractor.py", line 253, in extract
    go_file_json = json.loads(bytes(output))
  File "/usr/lib64/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

Solution: https://stackoverflow.com/questions/6862770/python-3-let-json-object-accept-bytes-or-let-urlopen-output-strings

```
Traceback (most recent call last):
  File "/tmp/env3/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/tmp/env3/bin/gofedlib-cli", line 59, in get_dependencies
    dependencies[key] = ippaths2providers(dependencies[key])
  File "/tmp/env3/bin/gofedlib-cli", line 24, in ippaths2providers
    decomposer = ImportPathsDecomposerBuilder().buildLocalDecomposer()
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/go/importpath/decomposerbuilder.py", line 7, in buildLocalDecomposer
    ipparser = ImportPathParserBuilder().buildWithLocalMapping()
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/go/importpath/parserbuilder.py", line 9, in __init__
    self.mapping = LibConfig().ipparserMapping()
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/config/libconfig.py", line 6, in __init__
    Config.__init__(self, "lib.conf")
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/config/config.py", line 18, in __init__
    self._parse(config_default)
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/config/config.py", line 24, in _parse
    self._config = ConfigParser.ConfigParser()
NameError: name 'ConfigParser' is not defined

```

Solution: https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser

```
Traceback (most recent call last):
  File "/tmp/env3/bin/gofedlib-cli", line 115, in <module>
    print(dict2json(result, args.pretty))
  File "/tmp/env3/bin/gofedlib-cli", line 16, in dict2json
    return json.dumps(o)
  File "/usr/lib64/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <map object at 0x7fa367db87b8> is not JSON serializable
```

Solution - https://stackoverflow.com/questions/33989430/map-object-is-not-json-serializable

And also Python3 style relative imorts - https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

**Comment by tuxdna** [comment]
Closed via https://github.com/gofed/gofedlib/pull/15
