### ISSUE TITLE
Gofedlib cli fails with analyzing a kubernetes project

### ISSUE THREAD

**Issue by tuxdna** [gofed/gofedlib#16]
I tried to run gofedlib CLI on project https://github.com/kubernetes/kompose

```
cd /tmp
git clone git@github.com:kubernetes/kompose.git
```

The output has error

```

$ gofedlib-cli --dependencies-main --dependencies-packages /tmp/kompose
ERROR:root:Import path prefix for 'appengine_internal' not recognized
ERROR:root:Import path prefix for 'context' not recognized
ERROR:root:Import path prefix for 'cloud.google.com/go/internal' not recognized
ERROR:root:Import path prefix for 'appengine_internal/base' not recognized
ERROR:root:Import path prefix for 'cloud.google.com/go/compute/metadata' not recognized
Traceback (most recent call last):
  File "/tmp/env3/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/tmp/env3/bin/gofedlib-cli", line 59, in get_dependencies
    dependencies[key] = ippaths2providers(dependencies[key])
  File "/tmp/env3/bin/gofedlib-cli", line 32, in ippaths2providers
    result.append(project_provider.parse(prefix).prefix())
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/providers/upstreamprovider.py", line 49, in parse
    info = self._parsePrefix(url)
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/providers/upstreamprovider.py", line 91, in _parsePrefix
    return self.parseGolangorgImportPath(url)
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/providers/upstreamprovider.py", line 235, in parseGolangorgImportPath
    raise ValueError("Import path %s is not in golang.org/x/<repo> form" % path)
ValueError: Import path k8s.io/client-go is not in golang.org/x/<repo> form
```

Apparently the handler for `k8s.io/client-go` type of urls is not yet supported.

How should we handle such a scenario?

**Comment by tuxdna** [comment]
**For Python2.7**, the above error was happening when gofedlib was installed via pip from  PyPI index. After **install from master branch**, correct output is shown.  Demonstrated below:

Install via pip:

```
(env2) $ pip install gofedlib
Installing collected packages: gofedlib
Successfully installed gofedlib-0.1.0a2
```

Analyze the package:

```
(env2) $ gofedlib-cli -j -d -t -m /home/saleem/work/learn/kompose
ERROR:root:Import path prefix for 'appengine_internal' not recognized
ERROR:root:Import path prefix for 'cloud.google.com/go/compute/metadata' not recognized
ERROR:root:Import path prefix for 'appengine_internal/base' not recognized
ERROR:root:Import path prefix for 'cloud.google.com/go/internal' not recognized
ERROR:root:Import path prefix for 'context' not recognized
Traceback (most recent call last):
  File "/tmp/env2/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/tmp/env2/bin/gofedlib-cli", line 59, in get_dependencies
    dependencies[key] = ippaths2providers(dependencies[key])
  File "/tmp/env2/bin/gofedlib-cli", line 32, in ippaths2providers
    result.append(project_provider.parse(prefix).prefix())
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/providers/upstreamprovider.py", line 39, in parse
    info = self._parsePrefix(url)
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/providers/upstreamprovider.py", line 81, in _parsePrefix
    raise UnsupportedImportPathError("Import path %s not supported" % url)
lib.types.UnsupportedImportPathError: Import path k8s.io/client-go not supported
```

Now install from master branch of gofedlib
```
python setup.py install
```

Analyze the package:
```
(env2) $ gofedlib-cli -j -d -t -m /home/saleem/work/learn/kompose
{
  "deps-main": [
    "https://github.com/kubernetes/kompose"
  ],
  "deps-packages": [
    "https://github.com/spf13/cobra",
    "https://github.com/kubernetes/kubernetes",
    "https://github.com/go-yaml/yaml",
    "https://github.com/docker/libcompose",
    "https://github.com/spf13/viper",
    "https://github.com/ghodss/yaml",
    "https://github.com/novln/docker-parser",
    "https://github.com/fatih/structs",
    "https://github.com/pkg/errors",
    "https://github.com/Sirupsen/logrus",
    "https://github.com/fsouza/go-dockerclient",
    "https://github.com/openshift/origin",
    "https://github.com/docker/cli",
    "https://github.com/kubernetes/kompose"
  ],
  "deps-tests": [
    "https://github.com/kubernetes/kubernetes",
    "https://github.com/docker/libcompose",
    "https://github.com/pkg/errors",
    "https://github.com/openshift/origin",
    "https://github.com/docker/cli",
    "https://github.com/kubernetes/kompose"
  ]
}
```

**Comment by tuxdna** [comment]
For Python3.x though it is still failing:

```
$ gofedlib-cli -j -d -t -m /home/saleem/work/learn/kompose
Traceback (most recent call last):
  File "/tmp/env3/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/go/functions.py", line 8, in project_packages
    return GoSymbolsExtractor(source_code_directory).extract().packages()
  File "/tmp/env3/lib/python3.5/site-packages/gofedlib/go/symbolsextractor/extractor.py", line 334, in extract
    package_imports[prefix] = package_imports[prefix] + i_paths
TypeError: unsupported operand type(s) for +: 'map' and 'map'
```

**Comment by ingvagabund** [comment]
The mapping [1] must be up2date with the one in the repo. The idea was the pull the file everytime (or when a special flag is set) from the web (or a db). Yet, it still needs to be implemented.

[1] https://github.com/gofed/gofedlib/blob/master/gofedlib/providers/data/ip2pp_mapping.json

**Comment by tuxdna** [comment]
Just a note that with python 2.7, there is an error if input path has trailing slash:

```
$ gofedlib-cli --dependencies-main --dependencies-packages /home/saleem/work/learn/kompose/
Traceback (most recent call last):
  File "/home/saleem/rhat/bayesian/github/common/env2/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/home/saleem/rhat/bayesian/github/common/env2/lib/python2.7/site-packages/gofedlib/go/functions.py", line 8, in project_packages
    return GoSymbolsExtractor(source_code_directory).extract().packages()
  File "/home/saleem/rhat/bayesian/github/common/env2/lib/python2.7/site-packages/gofedlib/go/symbolsextractor/extractor.py", line 239, in extract
    cme.extract()
  File "/home/saleem/rhat/bayesian/github/common/env2/lib/python2.7/site-packages/gofedlib/go/contentmetadataextractor.py", line 159, in extract
    self._orNodes()
  File "/home/saleem/rhat/bayesian/github/common/env2/lib/python2.7/site-packages/gofedlib/go/contentmetadataextractor.py", line 53, in _orNodes
    _or = _or or self._orNodes("%s/%s" % (node, n))
  File "/home/saleem/rhat/bayesian/github/common/env2/lib/python2.7/site-packages/gofedlib/go/contentmetadataextractor.py", line 49, in _orNodes
    if self._nodes[node] == []:
KeyError: '/script'
```

Same as this issue: https://github.com/gofed/gofedlib/issues/21

**Comment by tuxdna** [comment]
Works now via #21
