### ISSUE TITLE
Gives key error of .git when running on a git repository

### ISSUE THREAD

**Issue by tuxdna** [gofed/gofedlib#18]
Git clone a go project:

```
git clone git@github.com:cloudflare/hellogopher.git
```

Now run gofedlib on the project

```
$ ./gofedlib-cli -a /home/saleem/work/learn/go-projects/context/
Traceback (most recent call last):
  File "./gofedlib-cli", line 99, in <module>
    result['api'] = api(args.path)
  File "/home/saleem/work/learn/gofedlib/gofedlib/go/functions.py", line 5, in api
    return GoSymbolsExtractor(source_code_directory).extract().exportedApi()
  File "/home/saleem/work/learn/gofedlib/gofedlib/go/symbolsextractor/extractor.py", line 239, in extract
    cme.extract()
  File "/home/saleem/work/learn/gofedlib/gofedlib/go/contentmetadataextractor.py", line 159, in extract
    self._orNodes()
  File "/home/saleem/work/learn/gofedlib/gofedlib/go/contentmetadataextractor.py", line 53, in _orNodes
    _or = _or or self._orNodes("%s/%s" % (node, n))
  File "/home/saleem/work/learn/gofedlib/gofedlib/go/contentmetadataextractor.py", line 49, in _orNodes
    if self._nodes[node] == []:
KeyError: '/.git'

```

**Comment by tuxdna** [comment]
Works on python2.7 now. Marking as closed.
