### ISSUE TITLE
Update latest gofedlib to pypi index

### ISSUE THREAD

**Issue by tuxdna** [gofed/gofedlib#20]
The version of gofedlib on PyPI index is very old

 * https://pypi.python.org/pypi/gofedlib/0.1.0a2

A new release is needed to incorporate the changes made so far in master branch.

Here is one case where it will be useful: https://github.com/gofed/gofedlib/issues/16#issuecomment-330161685

**Comment by tuxdna** [comment]
@ingvagabund Can you please make a new release?

**Comment by fridex** [comment]
> @ingvagabund Can you please make a new release?

I can do it - @ingvagabund are you fine with a new release? BTW do you have a PyPI account so I can add you as owner of this package?

**Comment by tuxdna** [comment]
@fridex My account is  ` tuxdna` on PyPI

**Comment by jpopelka** [comment]
ping, what about the release ?

**Comment by fridex** [comment]
A new release has been pushed to PyPI, see gofedlib-0.1.0. I've added @ingvagabund as a package owner.

**Comment by jpopelka** [comment]
Looks OK on Fedora, but on centos I'm seeing:

```
$ docker run -ti centos bash
$ yum install -y epel-release && yum install python2-pip && pip2 install gofedlib
...
Installing collected packages: MarkupSafe, Jinja2, six, munch, chardet, certifi, urllib3, idna, requests, beautifulsoup4, lockfile, openidc-client, python-fedora, pyjwt, PyGithub, python-hglib, gofedlib
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for munch ... done
  Found existing installation: chardet 2.2.1
    Uninstalling chardet-2.2.1:
      Successfully uninstalled chardet-2.2.1
  Running setup.py install for openidc-client ... done
  Running setup.py install for python-fedora ... done
  Running setup.py install for PyGithub ... done
  Running setup.py install for python-hglib ... done
  Running setup.py install for gofedlib ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-daMS2x/gofedlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-c39UhV-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
```

**Comment by tuxdna** [comment]
@jpopelka: I added `-egg` to pip2 once I tried your commands and here is what I get, `RuntimeError: /bin/sh: go: command not found`, as shown below:

```
# pip2 install --egg gofedlib
Collecting gofedlib
  Using cached gofedlib-0.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /usr/lib/python2.7/site-packages (from gofedlib)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /usr/lib/python2.7/site-packages (from gofedlib)
Requirement already satisfied (use --upgrade to upgrade): python-fedora>=0.5.6 in /usr/lib/python2.7/site-packages (from gofedlib)
Requirement already satisfied (use --upgrade to upgrade): PyGithub in /usr/lib/python2.7/site-packages (from gofedlib)
Requirement already satisfied (use --upgrade to upgrade): python-hglib in /usr/lib/python2.7/site-packages (from gofedlib)
Requirement already satisfied (use --upgrade to upgrade): munch in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): kitchen in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): urllib3 in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): lockfile in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): openidc-client in /usr/lib/python2.7/site-packages (from python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): pyjwt in /usr/lib64/python2.7/site-packages (from PyGithub->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->python-fedora>=0.5.6->gofedlib)
Requirement already satisfied (use --upgrade to upgrade): idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->python-fedora>=0.5.6->gofedlib)
Installing collected packages: gofedlib
  Running setup.py install for gofedlib ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VC3pTk/gofedlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cnmCSs-record/install-record.txt --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-VC3pTk/gofedlib/setup.py", line 84, in <module>
        keywords='gofed golang API dependencies',
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-VC3pTk/gofedlib/setup.py", line 25, in run
        self._compile_parsego()
      File "/tmp/pip-build-VC3pTk/gofedlib/setup.py", line 22, in _compile_parsego
        raise RuntimeError(stderr)
    RuntimeError: /bin/sh: go: command not found
    
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VC3pTk/gofedlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cnmCSs-record/install-record.txt --compile" failed with error code 1 in /tmp/pip-build-VC3pTk/gofedlib/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by jpopelka** [comment]
Oh, right, it works with `--egg` (after installing `golang`), but it'd be nice it worked also without the `--egg`, because I'm seeing:
`DEPRECATION: --egg has been deprecated and will be removed in the future. This flag is mutually exclusive with large parts of pip, and actually using it invalidates pip's ability to manage the installation process.`

**Comment by tuxdna** [comment]
Yeah, you are right. I guess that on CentOS the setuptools are probably old as described in this post: https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind

**Comment by tuxdna** [comment]
I guess we can close this issue now.
