### ISSUE TITLE
gofedlib-cli fails with trailing slashes on the input path

### ISSUE THREAD

**Issue by tuxdna** [gofed/gofedlib#21]
gofedlib-cli fails with trailing slashes on the input path

With trailing slashes:

```
$ gofedlib-cli -j -d -t -m /home/saleem/work/learn/go-projects/golang-example/
Traceback (most recent call last):
  File "/tmp/env2/bin/gofedlib-cli", line 109, in <module>
    result.update(get_dependencies(project_packages(args.path), selection))
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/go/functions.py", line 8, in project_packages
    return GoSymbolsExtractor(source_code_directory).extract().packages()
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/go/symbolsextractor/extractor.py", line 239, in extract
    cme.extract()
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/go/contentmetadataextractor.py", line 159, in extract
    self._orNodes()
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/go/contentmetadataextractor.py", line 53, in _orNodes
    _or = _or or self._orNodes("%s/%s" % (node, n))
  File "/tmp/env2/lib/python2.7/site-packages/gofedlib/go/contentmetadataextractor.py", line 49, in _orNodes
    if self._nodes[node] == []:
KeyError: '/gotypes'
```

Without trailing slashes

```
(env2) $ gofedlib-cli -j -d -t -m /home/saleem/work/learn/go-projects/golang-example
{
  "deps-main": [
    "https://github.com/golang/tools",
    "https://github.com/golang/example"
  ],
  "deps-packages": [],
  "deps-tests": []
}
```

**Comment by tuxdna** [comment]
Closing via #22
