### ISSUE TITLE
Gofedcli fails while analyzing kube-plex project

### ISSUE THREAD

**Issue by sunilk747** [gofed/gofedlib#25]
I tried to run gofed-cli on this repo - https://github.com/munnerz/kube-plex.
But I am getting error as:
``` 
ssamal@localhost ~/redhat $ gofedlib-cli --dependencies-main --dependencies-packages kube-plex
Traceback (most recent call last):
  File "/usr/bin/gofedlib-cli", line 114, in <module>
    result.update(get_dependencies(project_packages(args.path, skip_errors=args.skip_errors), selection))
  File "/usr/bin/gofedlib-cli", line 59, in get_dependencies
    dependencies[key] = ippaths2providers(dependencies[key])
  File "/usr/bin/gofedlib-cli", line 32, in ippaths2providers
    result.append(project_provider.parse(prefix).prefix())
  File "/usr/lib/python2.7/site-packages/gofedlib/providers/upstreamprovider.py", line 39, in parse
    info = self._parsePrefix(url)
  File "/usr/lib/python2.7/site-packages/gofedlib/providers/upstreamprovider.py", line 81, in _parsePrefix
    raise UnsupportedImportPathError("Import path %s not supported" % url)
lib.types.UnsupportedImportPathError: Import path k8s.io/api not supported
```
I followed the steps mentioned [here](https://github.com/gofed/gofedlib/issues/16), Installed it from the master branch but it didn't work.
Any help would be appreciated.

**Comment by tuxdna** [comment]
You may want to update the mapping of package name with it's repo, in the following file: 

```
gofedlib/providers/data/ip2pp_mapping.json
```

Add an entry like below:

```
{"ipprefix": "k8s.io/api","provider_prefix":"github.com/kubernetes/kubernetes"},

```

Also to skip any errors you can install from master and use the `-s` flag:

```
$ pip2 install --egg git+https://github.com/gofed/gofedlib.git@master
$ gofedlib-cli -s --dependencies-main --dependencies-packages `pwd`
{"deps-packages": [], "deps-main": ["https://github.com/munnerz/kube-plex", "https://github.com/kubernetes/kubernetes", "https://github.com/kubernetes/kubernetes", "https://github.com/kubernetes/client-go"]}
```

**Comment by sunilk747** [comment]
@tuxdna I tried the above steps but still showing the same error.

**Comment by tuxdna** [comment]
@sunilk747 You may want to update the mapping file in the location where you installed gofedlib.

Try to isolate the issue using a python 2.7 virtualenv.

**Comment by sunilk747** [comment]
@tuxdna Is gofedlib-cli iterate over all the files in a go project and parse the import statement for dependencies?
